travis:
  secure:
    BINSTAR_TOKEN: 0goGXKkAsnBHOAV5/5IPol3PVJKsc7ZfpXlr880ya5mTrH5N7Ba1b1FT+hWwtuQaHv1LLGMjkYpr64JgiTZXOHvVSK2SkX+9/u0rIDFg8smY01cUoMXR+I7G9GChefYNDSvPxhzxVE0TM5KjVC9mgkk1bQnfrKgJqn4CFEJv34NNSPt6fMGoubRPVafpVG7E/MBm4vG/RAcB6uuKPURv0wKJl/dy3L8phr997WaElBlsuwDPfvSsDFONNs4mJTzMBgB+dj7rXrXXrrl6lE7dJXWBivUmknwLOGE/qkxveGB5Q/8ZOJoQtbJAQoeI7N2HC2L2bVk1MvnF4+1ip0slOOJd6e4ezxU7yPO9zc8GSQheo+U0LfCOkJ1o0/t8mkTY+24fgLc4fYRoOPpgps1KHSmaa3dOM/qvyvjeDy9m2cGrs2NP/VwLVqd48yJAkAg5PiOWyZ0Z7pf9SJw3+PGi2wX284FlAf28SMxJr6L8LFDtw20mKcd7iJ4rBPUwgXq9/9kUcQQwAUzQ1xGrc05l5gqermF3Te1dAiCmhWWy3ew95fDqHLAtRBjfRL68gaLt21kkzp5W72l5iKvBmCUimSJTK9bVQ1up27xHmVWjLKsRpivVoi7Yxvpb0/yBf2f/1m9fHi3fCgnZFwD2SmUFG63NHF36ThrTsgOcV7/2fC8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
