travis:
  secure:
    BINSTAR_TOKEN: Tb1jNSQ+o4D/sIVqSCeSMhILgVKlNQH5HFlJmxo8b3mFrXrSqwUmbBQ9Y9Pgigb4N0Bvk7ZsfSGXSphwT63waEBdRJwqFHAjziGPO7KBGmIQRrE7fRPE023uR3px1gB4v5/yzppCD5ZJOrh/+cVmUj38UYiQBiHilVy3weHTh1rOfQcD6RNyGjKhyLt95FXf0OALGynmKcx8dcKX8I0DkhiPX7AN+Tb7RAb2go3k5qFpHCIsL1OP2DY+yYVpD8jMLHf6bv0TEs9WDD6J9othvR5fE1INAvGtvPjafnyT7D6TU8HmhUhtw74ijtXlw7xmr9znsSuv+w5S/ES/a5ijcPs6tFqKiXy4IIaZg5qoUu+EBqm2lhOwCF76Gz7xoRldSSMx318S9SZQIZRFCKsxWyWiOw1sbZbCsSCs7+Ybb/IJ2ZWYYbbfX8RYYz86upGuKUBnqm3Fh3n8rKvBzGbQ4tfrqmZhpF2q8b6x04hQe/zMwRjzzQ9Vgi/z7Iku1Bw1bt1M3GHBQnvCvz5RLCW4oisQTLCID5jiVeL0RebNZCd90V+pAkiAYP+m9I+QLIcVJ+hOu+B+Y0oFMJQp1N1F4RXfjU+4kFWJJEQ0sRBlXLNb9Y+Oehc+lQBp9jtWOFd3U8cQcQTnsA+uE5zjkE+wfQKMqLDT0PI0iApI+ZiciWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
