travis:
  secure:
    BINSTAR_TOKEN: SK4Iflf+yVk0Qt03w/eocqxGz67p+2A+u3uVoj5RQZB1ZJ2eaduKsC7RdhbqK+mYV6WLPmsStWuaEOvDcUlnRUH9XpqhAjyzxuHxftMmT5TVWb7igeQ8rDMI817CamIViuW1PJO7xVXca3xtox5fMwa8xMGe1Wnrq8CdHk2WHpIf/dxAg7iO+FfUSDHwYkG286zaF05Tc91pFSkBi/0x0mtD1BOCzHR2jn2LTKl4RuAml1mIXjd6Dsay/ZZTsCRxt8f+rm5oQ2VqlaOs0Iwm+SXk4aTBp+Q5kembHnakdChpfOAvbCdYDnRZZVda8MNaU/NOJNO1Y2DT/2WgvPGMjuoBhR6uUZq2X/G4lvO1MzQkJa5V/k/2MOFfTeeIyG8E1hboBMv5/7P2PVpVe1bQA0J4wXeQ4CFB/IIrV5ogYMjVnAZ08JeJAOTeZj1+gwqBg0y/QWoWtV561yRrIeGGd+jxmoQVtGGamjp3mv0GENl5+kkvnlJ/PVbFvFJlfOH7Pi3YzGNI40ZjuO7fbylJO+8jDtvRXX8saMvsQpsBxylHq541Jp3OorodNjiW2wp+qBPh3bHQwg+qgC8vJYJbB+EJYRDyIm/msH7coSU1pPwy3BCYAeYPOkm9Kyfu9v7EBHOGK20Rv+XwAPg5yQJMBSApSxo/l1rlHUBQRD1cwg4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
